import { ChatConversation, ChatMessage } from '../../../navigation/types';

export const MOCK_CONVERSATIONS: ChatConversation[] = [
  {
    id: '1',
    title: 'Building A Administrators',
    participants: [
      {
        id: '101',
        name: 'Arben Hoxha',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/32.jpg',
        isOnline: true,
      },
      {
        id: '102',
        name: 'Sara Mati',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/women/44.jpg',
        isOnline: false,
        lastSeen: '2023-05-15T14:30:00Z',
      },
    ],
    lastMessage: {
      id: 'm1',
      conversationId: '1',
      senderId: '101',
      senderName: 'Arben Hoxha',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      content: 'We need to discuss the maintenance schedule for next month',
      timestamp: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
      readBy: ['101', '102'],
      status: 'read',
    },
    unreadCount: 0,
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    isGroup: true,
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGJ1aWxkaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
  },
  // Add a Community Chat conversation
  {
    id: '6',
    title: 'Community Chat',
    participants: [
      {
        id: '101',
        name: 'Arben Hoxha',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/32.jpg',
        isOnline: true,
      },
      {
        id: '102',
        name: 'Sara Mati',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/women/44.jpg',
        isOnline: false,
      },
      {
        id: '108',
        name: 'Liri Berisha',
        role: 'resident',
        image: 'https://randomuser.me/api/portraits/women/68.jpg',
        isOnline: true,
      },
    ],
    lastMessage: {
      id: 'm6',
      conversationId: '6',
      senderId: '108',
      senderName: 'Liri Berisha',
      senderRole: 'resident',
      senderImage: 'https://randomuser.me/api/portraits/women/68.jpg',
      content: 'Will there be an option to join remotely for the community meeting?',
      timestamp: new Date(Date.now() - 345600000).toISOString(), // 4 days ago
      readBy: ['101', '102'],
      status: 'read',
    },
    unreadCount: 0,
    createdAt: '2023-03-05T15:45:00Z',
    updatedAt: new Date(Date.now() - 345600000).toISOString(),
    isGroup: true,
    image: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGNvbW11bml0eXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
  },
  {
    id: '2',
    title: 'Building B Team',
    participants: [
      {
        id: '103',
        name: 'Elton Zholi',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/55.jpg',
        isOnline: false,
        lastSeen: '2023-05-15T10:15:00Z',
      },
      {
        id: '104',
        name: 'Drita Koka',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/women/33.jpg',
        isOnline: true,
      },
    ],
    lastMessage: {
      id: 'm2',
      conversationId: '2',
      senderId: '104',
      senderName: 'Drita Koka',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/women/33.jpg',
      content: 'That sounds serious. Have you inspected it yourself?',
      timestamp: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
      readBy: ['104'],
      status: 'delivered',
    },
    unreadCount: 0,
    createdAt: '2023-02-20T11:30:00Z',
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
    isGroup: true,
    image: 'https://images.unsplash.com/photo-1554435493-93422e8d1a41?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGJ1aWxkaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
  },
  {
    id: '3',
    title: 'Arben Hoxha',
    participants: [
      {
        id: '101',
        name: 'Arben Hoxha',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/32.jpg',
        isOnline: true,
      },
    ],
    lastMessage: {
      id: 'm3',
      conversationId: '3',
      senderId: '101',
      senderName: 'Arben Hoxha',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      content: 'Hi Arben, of course. What\'s your proposal?',
      timestamp: new Date(Date.now() - 518400000).toISOString(), // 6 days ago
      readBy: ['101'],
      status: 'read',
    },
    unreadCount: 0,
    createdAt: '2023-03-10T08:45:00Z',
    updatedAt: new Date(Date.now() - 518400000).toISOString(),
    isGroup: false,
  },
  {
    id: '4',
    title: 'Maintenance Team',
    participants: [
      {
        id: '105',
        name: 'Gezim Basha',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/65.jpg',
        isOnline: false,
        lastSeen: '2023-05-14T18:20:00Z',
      },
      {
        id: '106',
        name: 'Teuta Leka',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/women/22.jpg',
        isOnline: true,
      },
      {
        id: '107',
        name: 'Dritan Mema',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/41.jpg',
        isOnline: true,
      },
    ],
    lastMessage: {
      id: 'm4',
      conversationId: '4',
      senderId: '107',
      senderName: 'Dritan Mema',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/men/41.jpg',
      content: 'We need to order new light fixtures for the hallways in Building C',
      timestamp: new Date(Date.now() - 259200000).toISOString(), // 3 days ago
      readBy: ['105', '106', '107'],
      status: 'read',
    },
    unreadCount: 0,
    createdAt: '2023-01-05T10:15:00Z',
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
    isGroup: true,
  },
  {
    id: '5',
    title: 'Arben Hoxha',
    participants: [
      {
        id: '103',
        name: 'Arben Hoxha',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/32.jpg',
        isOnline: true,
      },
    ],
    lastMessage: {
      id: 'm5',
      conversationId: '5',
      senderId: '103',
      senderName: 'Arben Hoxha',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      content: 'Hi John, the recycling bins should be placed by the entrance.',
      timestamp: new Date(Date.now() - 259200000).toISOString(), // 3 days ago
      readBy: ['103'],
      status: 'read',
    },
    unreadCount: 0,
    createdAt: '2023-02-08T14:30:00Z',
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
    isGroup: false,
  },
];

export const MOCK_CONVERSATIONS_MAP: Record<string, ChatConversation> = {
  '1': {
    id: '1',
    title: 'Building A Administrators',
    participants: [
      {
        id: '101',
        name: 'Arben Hoxha',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/32.jpg',
        isOnline: true,
      },
      {
        id: '102',
        name: 'Sara Mati',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/women/44.jpg',
        isOnline: false,
        lastSeen: '2023-05-15T14:30:00Z',
      },
    ],
    lastMessage: {
      id: 'm1',
      conversationId: '1',
      senderId: '101',
      senderName: 'Arben Hoxha',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      content: 'We need to discuss the maintenance schedule for next month',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      readBy: ['101', '102'],
      status: 'read',
    },
    unreadCount: 0,
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    isGroup: true,
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGJ1aWxkaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
  },
  '2': {
    id: '2',
    title: 'Building B Team',
    participants: [
      {
        id: '103',
        name: 'Elton Zholi',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/55.jpg',
        isOnline: false,
        lastSeen: '2023-05-15T10:15:00Z',
      },
      {
        id: '104',
        name: 'Drita Koka',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/women/33.jpg',
        isOnline: true,
      },
    ],
    lastMessage: {
      id: 'm2',
      conversationId: '2',
      senderId: '104',
      senderName: 'Drita Koka',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/women/33.jpg',
      content: 'The plumber will arrive tomorrow at 10 AM to fix the leak in apartment 302',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      readBy: ['104'],
      status: 'delivered',
    },
    unreadCount: 2,
    createdAt: '2023-02-20T11:30:00Z',
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    isGroup: true,
    image: 'https://images.unsplash.com/photo-1554435493-93422e8d1a41?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGJ1aWxkaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
  },
  '3': {
    id: '3',
    title: 'Arben Hoxha',
    participants: [
      {
        id: '101',
        name: 'Arben Hoxha',
        role: 'admin',
        image: 'https://randomuser.me/api/portraits/men/32.jpg',
        isOnline: true,
      },
    ],
    lastMessage: {
      id: 'm3',
      conversationId: '3',
      senderId: '101',
      senderName: 'Arben Hoxha',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      content: 'Thank you for approving the budget for the lobby renovation',
      timestamp: new Date(Date.now() - 172800000).toISOString(),
      readBy: ['101'],
      status: 'read',
    },
    unreadCount: 0,
    createdAt: '2023-03-10T08:45:00Z',
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
    isGroup: false,
  },
};

export const MOCK_MESSAGES: Record<string, ChatMessage[]> = {
  '1': [
    {
      id: 'm101',
      conversationId: '1',
      senderId: '101',
      senderName: 'Arben Hoxha',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      content: 'Good morning everyone. We need to discuss the maintenance schedule for Building A next month.',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      readBy: ['101', '102', 'manager'],
      status: 'read',
    },
    {
      id: 'm102',
      conversationId: '1',
      senderId: '102',
      senderName: 'Sara Mati',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/women/44.jpg',
      content: 'I agree. The elevator needs servicing and we need to schedule a time that minimizes disruption for residents.',
      timestamp: new Date(Date.now() - 6000000).toISOString(),
      readBy: ['101', '102', 'manager'],
      status: 'read',
    },
    {
      id: 'm103',
      conversationId: '1',
      senderId: 'manager',
      senderName: 'Elena Koci',
      senderRole: 'manager',
      content: 'Good point, Sara. Let\'s schedule the elevator maintenance for a weekday between 10am-2pm when most residents are at work. Arben, can you coordinate with the service provider?',
      timestamp: new Date(Date.now() - 5400000).toISOString(),
      readBy: ['101', '102', 'manager'],
      status: 'read',
    },
    {
      id: 'm104',
      conversationId: '1',
      senderId: '101',
      senderName: 'Arben Hoxha',
      senderRole: 'admin',
      senderImage: 'https://randomuser.me/api/portraits/men/32.jpg',
      content: 'Yes, I\'ll contact them today and propose next Tuesday. I\'ll send a notification to residents once it\'s confirmed.',
      timestamp: new Date(Date.now() - 4800000).toISOString(),
      readBy: ['101', '102', 'manager'],
      status: 'read',
    },
  ],
  '2': [],
  '3': []
}; 