// This file contains mock data used for development and testing

export const mockBuildings = [
  {
    id: '1',
    name: 'Sunset Apartments',
    address: '123 Main Street',
    units: 30,
    floors: 5,
    yearBuilt: 2010
  },
  {
    id: '2',
    name: 'Ocean View Residences',
    address: '456 Beach Road',
    units: 50,
    floors: 8,
    yearBuilt: 2015
  },
  {
    id: '3',
    name: 'Mountain Heights',
    address: '789 Summit Avenue',
    units: 20,
    floors: 4,
    yearBuilt: 2018
  }
];

export const mockProperties = [
  {
    id: '1',
    name: 'Apartment 101',
    buildingId: '1',
    floor: 1,
    size: 65,
    bedrooms: 1,
    bathrooms: 1,
    status: 'Occupied',
    residentId: '1',
    rent: 850
  },
  {
    id: '2',
    name: 'Apartment 102',
    buildingId: '1',
    floor: 1,
    size: 85,
    bedrooms: 2,
    bathrooms: 1,
    status: 'Vacant',
    residentId: null,
    rent: 1200
  },
  {
    id: '3',
    name: 'Apartment 201',
    buildingId: '1',
    floor: 2,
    size: 100,
    bedrooms: 2,
    bathrooms: 2,
    status: 'Occupied',
    residentId: '2',
    rent: 1350
  },
  {
    id: '4',
    name: 'Apartment 301',
    buildingId: '2',
    floor: 3,
    size: 120,
    bedrooms: 3,
    bathrooms: 2,
    status: 'Vacant',
    residentId: null,
    rent: 1600
  },
  {
    id: '5',
    name: 'Apartment 401',
    buildingId: '2',
    floor: 4,
    size: 150,
    bedrooms: 3,
    bathrooms: 2,
    status: 'Occupied',
    residentId: '3',
    rent: 1800
  }
];

// Mock maintenance request data
export const mockMaintenanceRequests = [
  {
    id: '1',
    title: 'Leaking faucet in kitchen',
    description: 'The kitchen sink faucet has been leaking steadily for two days. Water is pooling in the cabinet below.',
    type: 'plumbing',
    submitterId: '101',
    submitterName: 'Alex Johnson',
    unitId: '301',
    unitNumber: '12A',
    buildingId: '1',
    buildingName: 'Sunset Towers',
    location: 'Kitchen',
    status: 'open',
    priority: 'medium',
    createdAt: '2025-01-15T09:30:00Z',
    updatedAt: '2025-01-15T09:30:00Z',
    images: [
      'https://images.unsplash.com/photo-1585704032915-c3400ca199bc?w=600&auto=format',
    ],
    comments: [
      {
        id: '101',
        maintenanceRequestId: '1',
        author: 'Alex Johnson',
        authorId: '101',
        authorRole: 'resident',
        text: 'The leak seems to be getting worse since this morning',
        timestamp: '2025-01-15T14:20:00Z',
        createdAt: '2025-01-15T14:20:00Z',
      }
    ],
  },
  {
    id: '2',
    title: 'Air conditioning not working',
    description: 'AC unit is not cooling properly. Temperature reads 78°F despite setting at 68°F.',
    type: 'hvac',
    submitterId: '102',
    submitterName: 'Maya Rivera',
    unitId: '302',
    unitNumber: '8B',
    buildingId: '1',
    buildingName: 'Sunset Towers',
    location: 'Living Room',
    status: 'in-progress',
    priority: 'high',
    createdAt: '2025-01-14T16:45:00Z',
    updatedAt: '2025-01-16T10:15:00Z',
    assignedToId: '501',
    assignedToName: 'Technical Services Inc.',
    estimatedCost: 250,
    scheduledDate: '2025-01-17T13:00:00Z',
    comments: [
      {
        id: '201',
        maintenanceRequestId: '2',
        author: 'Admin User',
        authorId: '001',
        authorRole: 'administrator',
        text: 'HVAC technician has been scheduled for tomorrow at 1pm',
        timestamp: '2025-01-16T10:15:00Z',
        createdAt: '2025-01-16T10:15:00Z',
        isPrivate: false,
      }
    ],
  },
  {
    id: '3',
    title: 'Broken light fixture in hallway',
    description: 'The ceiling light in the main hallway has stopped working. Bulb replacement didn\'t fix the issue.',
    type: 'electrical',
    submitterId: '103',
    submitterName: 'Sam Taylor',
    unitId: '303',
    unitNumber: '5C',
    buildingId: '2',
    buildingName: 'Harbor View Residences',
    location: 'Hallway',
    status: 'resolved',
    priority: 'low',
    createdAt: '2025-01-10T08:20:00Z',
    updatedAt: '2025-01-12T15:45:00Z',
    assignedToId: '401',
    assignedToName: 'John Electrician',
    estimatedCost: 85,
    actualCost: 75,
    scheduledDate: '2025-01-12T10:00:00Z',
    startedAt: '2025-01-12T10:15:00Z',
    completedAt: '2025-01-12T11:30:00Z',
    resolutionDetails: 'Replaced faulty wiring in ceiling fixture and installed new LED fixture',
    comments: [
      {
        id: '301',
        maintenanceRequestId: '3',
        author: 'John Electrician',
        authorId: '401',
        authorRole: 'maintenance',
        text: 'Completed the repair. The issue was with the wiring, not the fixture itself.',
        timestamp: '2025-01-12T11:35:00Z',
        createdAt: '2025-01-12T11:35:00Z',
      }
    ],
  },
  {
    id: '4',
    title: 'Lobby door not closing properly',
    description: 'The main lobby entrance door doesn\'t close completely, creating a security concern.',
    type: 'security',
    submitterId: '001',
    submitterName: 'Admin User',
    buildingId: '2',
    buildingName: 'Harbor View Residences',
    location: 'Main Entrance',
    status: 'open',
    priority: 'urgent',
    createdAt: '2025-01-16T07:50:00Z',
    updatedAt: '2025-01-16T07:50:00Z',
    isRecurring: false,
  },
  {
    id: '5',
    title: 'Monthly HVAC Filter Replacement',
    description: 'Routine replacement of HVAC filters in all common areas',
    type: 'hvac',
    submitterId: '001',
    submitterName: 'Admin User',
    buildingId: '1',
    buildingName: 'Sunset Towers',
    location: 'All Common Areas',
    status: 'in-progress',
    priority: 'medium',
    createdAt: '2025-01-05T09:00:00Z',
    updatedAt: '2025-01-15T10:30:00Z',
    assignedToId: '402',
    assignedToName: 'Maintenance Team',
    isRecurring: true,
    recurringFrequency: 'monthly',
    nextRecurringDate: '2025-02-05T09:00:00Z',
  },
  {
    id: '6',
    title: 'Cracked tile in swimming pool',
    description: 'Several tiles on the north edge of the swimming pool are cracked and need replacement',
    type: 'structural',
    submitterId: '001',
    submitterName: 'Admin User',
    buildingId: '3',
    buildingName: 'Mountain View Apartments',
    location: 'Swimming Pool',
    status: 'open',
    priority: 'medium',
    createdAt: '2025-01-14T11:20:00Z',
    updatedAt: '2025-01-14T11:20:00Z',
    images: [
      'https://images.unsplash.com/photo-1576013551627-0fd24e859ede?w=600&auto=format',
    ],
  },
  {
    id: '7',
    title: 'Washing machine leaking',
    description: 'The washing machine in unit 3D is leaking water onto the floor during spin cycle',
    type: 'appliance',
    submitterId: '105',
    submitterName: 'Jordan Lee',
    unitId: '307',
    unitNumber: '3D',
    buildingId: '3',
    buildingName: 'Mountain View Apartments',
    location: 'Laundry Room',
    status: 'in-progress',
    priority: 'high',
    createdAt: '2025-01-15T13:10:00Z',
    updatedAt: '2025-01-16T09:45:00Z',
    assignedToId: '403',
    assignedToName: 'Appliance Repair Pro',
    scheduledDate: '2025-01-17T10:00:00Z',
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format',
    ],
    comments: [
      {
        id: '701',
        maintenanceRequestId: '7',
        author: 'Jordan Lee',
        authorId: '105',
        authorRole: 'resident',
        text: "I've placed towels around the machine to catch the water for now",
        timestamp: '2025-01-15T14:30:00Z',
        createdAt: '2025-01-15T14:30:00Z',
      },
      {
        id: '702',
        maintenanceRequestId: '7',
        author: 'Admin User',
        authorId: '001',
        authorRole: 'administrator',
        text: 'Technician will arrive tomorrow at 10am. Please be available to let them in.',
        timestamp: '2025-01-16T09:45:00Z',
        createdAt: '2025-01-16T09:45:00Z',
      }
    ],
  },
  {
    id: '8',
    title: 'Landscaping needed around north entrance',
    description: 'The bushes and plants around the north entrance are overgrown and need trimming',
    type: 'landscaping',
    submitterId: '001',
    submitterName: 'Admin User',
    buildingId: '1',
    buildingName: 'Sunset Towers',
    location: 'North Entrance',
    status: 'open',
    priority: 'low',
    createdAt: '2025-01-16T08:30:00Z',
    updatedAt: '2025-01-16T08:30:00Z',
  }
];

// Mock maintenance workers data
export const mockMaintenanceWorkers = [
  {
    id: '401',
    name: 'John Electrician',
    email: 'john@example.com',
    phone: '(555) 123-4567',
    specialties: ['electrical', 'appliance'],
    isExternal: true,
    company: 'City Electric Services',
    availability: 'available',
    assignedRequests: 0,
    completedRequests: 17,
    averageResolutionTime: 2.5,
    image: 'https://randomuser.me/api/portraits/men/44.jpg',
  },
  {
    id: '402',
    name: 'Maintenance Team',
    email: 'maintenance@example.com',
    phone: '(555) 234-5678',
    specialties: ['hvac', 'plumbing', 'common_area', 'landscaping'],
    isExternal: false,
    availability: 'busy',
    assignedRequests: 3,
    completedRequests: 42,
    averageResolutionTime: 6.2,
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    id: '403',
    name: 'Appliance Repair Pro',
    email: 'repair@example.com',
    phone: '(555) 345-6789',
    specialties: ['appliance', 'electrical'],
    isExternal: true,
    company: 'Appliance Experts Inc.',
    availability: 'available',
    assignedRequests: 1,
    completedRequests: 8,
    averageResolutionTime: 3.0,
    image: 'https://randomuser.me/api/portraits/women/28.jpg',
  },
  {
    id: '404',
    name: 'Sarah Plumber',
    email: 'sarah@example.com',
    phone: '(555) 456-7890',
    specialties: ['plumbing', 'appliance'],
    isExternal: true,
    company: 'Reliable Plumbing Inc.',
    availability: 'unavailable',
    assignedRequests: 0,
    completedRequests: 12,
    averageResolutionTime: 1.8,
    image: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
  {
    id: '405',
    name: 'Structural Specialists',
    email: 'structures@example.com',
    phone: '(555) 567-8901',
    specialties: ['structural', 'common_area'],
    isExternal: true,
    company: 'Building Integrity LLC',
    availability: 'available',
    assignedRequests: 0,
    completedRequests: 5,
    averageResolutionTime: 12.4,
    image: 'https://randomuser.me/api/portraits/men/52.jpg',
  },
  {
    id: '501',
    name: 'Technical Services Inc.',
    email: 'hvac@example.com',
    phone: '(555) 678-9012',
    specialties: ['hvac', 'electrical'],
    isExternal: true,
    company: 'Technical Services Inc.',
    availability: 'busy',
    assignedRequests: 1,
    completedRequests: 35,
    averageResolutionTime: 4.5,
    image: 'https://randomuser.me/api/portraits/women/45.jpg',
  }
];

// Mock maintenance analytics
export const mockMaintenanceAnalytics = {
  totalRequests: 127,
  openRequests: 47,
  inProgressRequests: 32,
  resolvedRequests: 42,
  cancelledRequests: 6,
  averageResolutionTime: 18.5, // hours
  requestsByType: [
    { type: 'plumbing', count: 36, percentage: 28.3 },
    { type: 'electrical', count: 24, percentage: 18.9 },
    { type: 'hvac', count: 19, percentage: 15.0 },
    { type: 'appliance', count: 17, percentage: 13.4 },
    { type: 'structural', count: 11, percentage: 8.7 },
    { type: 'common_area', count: 9, percentage: 7.1 },
    { type: 'landscaping', count: 5, percentage: 3.9 },
    { type: 'security', count: 4, percentage: 3.1 },
    { type: 'other', count: 2, percentage: 1.6 }
  ],
  requestsByPriority: [
    { priority: 'low', count: 38, percentage: 29.9 },
    { priority: 'medium', count: 52, percentage: 40.9 },
    { priority: 'high', count: 30, percentage: 23.6 },
    { priority: 'urgent', count: 7, percentage: 5.5 }
  ],
  costSummary: {
    totalEstimated: 12750,
    totalActual: 10980,
    averagePerRequest: 261.43
  },
  monthlySummary: [
    { month: 'Jan', requestCount: 127, resolutionRate: 33.1, averageCost: 261.43 },
    { month: 'Dec', requestCount: 116, resolutionRate: 87.9, averageCost: 243.52 },
    { month: 'Nov', requestCount: 98, resolutionRate: 95.9, averageCost: 258.17 },
    { month: 'Oct', requestCount: 107, resolutionRate: 92.5, averageCost: 274.36 },
    { month: 'Sep', requestCount: 89, resolutionRate: 97.8, averageCost: 235.91 },
    { month: 'Aug', requestCount: 103, resolutionRate: 94.2, averageCost: 267.80 }
  ]
}; 